version: '3'
services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: ${REDIS_IMAGE_BASE}:${REDIS_IMAGE_TAG}
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ${REDIS_CONFIG_FILE}:/usr/local/etc/redis/redis.conf.example
    environment:
      - TZ="${TZ}"
