version: '3'
services:
  mongodb:
    container_name: ${MONGODB_CONTAINER_NAME}
    image: ${MONGODB_IMAGE_BASE}:${MONGODB_IMAGE_TAG}
    restart: always
    ports:
      - ${MONGODB_HOST_PORT}:27017
    volumes:
      - ${MONGODB_DATA_DIR}:/bitnami/mongodb
    environment:
      - TZ="${TZ}"
      - ALLOW_EMPTY_PASSWORD=${MONGODB_ALLOW_EMPTY_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
