version: '3'
services:
  es1:
    container_name: ${ES1_CONTAINER_NAME}
    image: ${ES1_IMAGE_BASE}:${ES1_IMAGE_TAG}
    command: ["elasticsearch", "-Xms1g", "-Xmx1g", "--cluster.name=openedx", "--bootstrap.mlockall=true"]
    ports:
      - ${ES1_PORT_1}:9200
      - ${ES1_PORT_2}:9300  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ${ES1_DATA_FILE}:/usr/share/elasticsearch/data