version: '3'
services:
  zookeeper:
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    image: ${ZOOKEEPER_IMAGE_BASE}:${ZOOKEEPER_IMAGE_TAG}
    restart: always
    ports:
      - ${ZOOKEEPER_HOST_PORT}:2181
    volumes:
      - ${ZOOKEEPER_DATA_DIR}:/bitnami/zookeeper
    environment:
      - TZ="${TZ}"
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=${ZOOKEEPER_SERVER_USERS}
      - ZOO_SERVER_PASSWORDS=${ZOOKEEPER_SERVER_PASSWORDS}
      - ZOO_CLIENT_USER=${ZOOKEEPER_CLIENT_USER}
      - ZOO_CLIENT_PASSWORD=${ZOOKEEPER_CLIENT_PASSWORD}